/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

/**
 *
 * @author mytcr
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInterpolacion = new javax.swing.JButton();
        btnBusquedaBinaria = new javax.swing.JButton();
        btnBusquedaLineal1 = new javax.swing.JButton();
        btnBusquedaLineal = new javax.swing.JButton();
        txtVector = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInterpolacion.setBackground(new java.awt.Color(255, 255, 255));
        btnInterpolacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInterpolacion.setText("Busqueda Interpolacion");
        btnInterpolacion.setBorder(null);
        btnInterpolacion.setBorderPainted(false);
        btnInterpolacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterpolacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInterpolacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 210, 30));

        btnBusquedaBinaria.setBackground(new java.awt.Color(255, 255, 255));
        btnBusquedaBinaria.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBusquedaBinaria.setText("BusquedaBinaria");
        btnBusquedaBinaria.setBorder(null);
        btnBusquedaBinaria.setBorderPainted(false);
        btnBusquedaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaBinariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusquedaBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, 30));

        btnBusquedaLineal1.setBackground(new java.awt.Color(255, 255, 255));
        btnBusquedaLineal1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBusquedaLineal1.setText("Busqueda Lineal String");
        btnBusquedaLineal1.setBorder(null);
        btnBusquedaLineal1.setBorderPainted(false);
        btnBusquedaLineal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaLineal1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusquedaLineal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 210, 30));

        btnBusquedaLineal.setBackground(new java.awt.Color(255, 255, 255));
        btnBusquedaLineal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBusquedaLineal.setText("Busqueda Lineal");
        btnBusquedaLineal.setBorder(null);
        btnBusquedaLineal.setBorderPainted(false);
        btnBusquedaLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaLinealActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusquedaLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, 30));
        jPanel1.add(txtVector, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Vector:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Datos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));
        jPanel1.add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, -1));

        lblResultado.setBackground(new java.awt.Color(255, 255, 255));
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("IndiceResultado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Métodos de Busqueda");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInterpolacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterpolacionActionPerformed
        int dato = Integer.parseInt(txtDato.getText());
        int[] vector = newpackage.ConvertirVectores.AVectorEntero(txtVector.getText());
        int indice = BusquedaInterpolacion.interpolationSearch(vector, dato);
        lblResultado.setText(Integer.toString(indice));
    }//GEN-LAST:event_btnInterpolacionActionPerformed

    private void btnBusquedaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaBinariaActionPerformed
        int dato = Integer.parseInt(txtDato.getText());
        int[] vector = newpackage.ConvertirVectores.AVectorEntero(txtVector.getText());
        int indice = BusquedaBinaria.busqueda(vector, dato);
        lblResultado.setText(BusquedaBinaria.numero);
    }//GEN-LAST:event_btnBusquedaBinariaActionPerformed

    private void btnBusquedaLineal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaLineal1ActionPerformed
        String dato = txtDato.getText();
        String cadena = txtVector.getText();
        String[] v = cadena.split(",");
        BusquedaLineal.busquedaSecuencial1(v, dato);
        String indice =  BusquedaLineal.posicion1;
        lblResultado.setText(indice);
    }//GEN-LAST:event_btnBusquedaLineal1ActionPerformed

    private void btnBusquedaLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaLinealActionPerformed
        int dato = Integer.parseInt(txtDato.getText());
        int[] vector = newpackage.ConvertirVectores.AVectorEntero(txtVector.getText());
        BusquedaLineal.busquedaSecuencial(vector, dato);
        String indice =  BusquedaLineal.posicion1;
        lblResultado.setText(indice);
        //txtVector.setText(Convertir.ConvertirVectores.ACadena(vector));
    }//GEN-LAST:event_btnBusquedaLinealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaBinaria;
    private javax.swing.JButton btnBusquedaLineal;
    private javax.swing.JButton btnBusquedaLineal1;
    private javax.swing.JButton btnInterpolacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextField txtVector;
    // End of variables declaration//GEN-END:variables
}
